create or replace NONEDITIONABLE FUNCTION FUN_ENCRIPTA (pCADENA IN VARCHAR2) RETURN VARCHAR2 IS

    nINDICE NUMBER;
    sRESULTADO VARCHAR2(100);
    sCARACTER CHAR(1);

BEGIN

    nINDICE := 0;
    sRESULTADO := '';

    IF pCADENA IS NOT NULL THEN
        LOOP
            EXIT WHEN nINDICE > LENGTH(pCADENA);
            nINDICE := nINDICE + 1;
            sCARACTER := SUBSTR (pCADENA, nINDICE, 1);
            sCARACTER := CHR( ASCII (sCARACTER) - 7);
            sRESULTADO := sRESULTADO || sCARACTER;
        END LOOP;
    END IF;

    RETURN sRESULTADO;

END FUN_ENCRIPTA;