create or replace NONEDITIONABLE FUNCTION FUN_IMPUESTO_SUELDO (OPCION IN NUMBER, SUELDO IN NUMBER) RETURN NUMBER IS

    LV_LIMIT_SEM               SYSTEM.ISR_SEMANAL.LIM_INF%TYPE;
    LV_LIMIT_QUI               SYSTEM.ISR_QUINCENAL.LIM_INF%TYPE;
    LV_LIMIT_MEN               SYSTEM.ISR_MENSUAL.LIM_INF%TYPE;
    LV_PORCENTAJE               NUMBER;
    LV_CUOTAFIJA                NUMBER;
    LV_OPERACION                NUMBER;
    LV_IMP_RESULTADO            NUMBER;

BEGIN
    IF OPCION = 1 THEN --SEMANAL
        --CONSULTA TABLA DE IMPUESTOS SEMANALES
        BEGIN 
            SELECT LIM_INF, CUOTA_FIJA, PORCENTAJE INTO LV_LIMIT_SEM, LV_CUOTAFIJA, LV_PORCENTAJE FROM ISR_SEMANAL WHERE SUELDO BETWEEN LIM_INF AND LIM_SUP;
        EXCEPTION
            WHEN OTHERS THEN
                dbms_output.put_line('ERROR: '|| sqlerrm);
        END;

        LV_OPERACION := (SUELDO - LV_LIMIT_SEM);
        LV_OPERACION := (LV_OPERACION * (LV_PORCENTAJE/100));
        LV_IMP_RESULTADO := ROUND((LV_OPERACION + LV_CUOTAFIJA),2);

    END IF;

    IF OPCION = 2 THEN --QUINCENAL
        --CONSULTA TABLA DE IMPUESTOS SEMANALES
        BEGIN 
            SELECT LIM_INF, CUOTA_FIJA, PORCENTAJE INTO LV_LIMIT_QUI, LV_CUOTAFIJA, LV_PORCENTAJE FROM ISR_QUINCENAL WHERE SUELDO BETWEEN LIM_INF AND LIM_SUP;
        EXCEPTION
            WHEN OTHERS THEN
                dbms_output.put_line('ERROR: '|| sqlerrm);
        END;

        LV_OPERACION := (SUELDO - LV_LIMIT_QUI);
        LV_OPERACION := (LV_OPERACION * (LV_PORCENTAJE/100));
        LV_IMP_RESULTADO := ROUND((LV_OPERACION + LV_CUOTAFIJA),2);

    END IF;

    IF OPCION = 3 THEN --MENSUAL
        --CONSULTA TABLA DE IMPUESTOS SEMANALES
        BEGIN 
            SELECT LIM_INF, CUOTA_FIJA, PORCENTAJE INTO LV_LIMIT_MEN, LV_CUOTAFIJA, LV_PORCENTAJE FROM ISR_MENSUAL WHERE SUELDO BETWEEN LIM_INF AND LIM_SUP;
        EXCEPTION
            WHEN OTHERS THEN
                dbms_output.put_line('ERROR: '|| sqlerrm);
        END;

        LV_OPERACION := (SUELDO - LV_LIMIT_MEN);
        LV_OPERACION := (LV_OPERACION * (LV_PORCENTAJE/100));
        LV_IMP_RESULTADO := ROUND((LV_OPERACION + LV_CUOTAFIJA),2);

    END IF;

    RETURN LV_IMP_RESULTADO;

END FUN_IMPUESTO_SUELDO;
