--INSERCION DE DATO PARA BUSCAR DESPUES
INSERT INTO PR_EMPLOYEES (EMP_NAME, EMAIL, JOB_ID, SALARY) VALUES ('A_B PRUEBA','A_B@CORREO.MX', 4, 2100);
/
COMMIT;
/
/*SELECT PARA BUSQUEDA DE EMPLEADOS, USANDO UN CARACTER ESCAPE PARA QUE TOME UN CARACTER LITERALMENTE Y NO COMO UN CARACTER ESPECIAL DE BUSQUEDA*/
SELECT * FROM PR_EMPLOYEES
WHERE 1=1
AND EMP_NAME LIKE 'A/_B%' ESCAPE '/'
;
/*SELECT PARA BUSQUEDA DE EMPLEADOS, USANDO UN CARACTER ESPECIAL DE BUSQUEDA (_) Y (%)*/
SELECT * FROM PR_EMPLOYEES
WHERE 1=1
AND EMP_NAME LIKE 'A_%'
;
/
/*VERIFICACION DE CHAR Y VARCHAR2*/
CREATE TABLE PATO (FI CHAR(6), FA VARCHAR2(6));
/
INSERT INTO PATO VALUES ('CUAK','CUAK');
/
COMMIT;
/
/*VALIDACION DE LOS CAMPOS ANTERIORES CHAR Y VARCHAR2*/
SELECT '*'||FI||'*' CHAR1, '*'||FA||'*' VAR2 FROM PATO;
/

INSERT INTO PR_EMPLOYEES (EMP_NAME, EMAIL, JOB_ID, SALARY) VALUES ('STEVEN','STEVEN@CORREO.MX', 2, 2100);
INSERT INTO PR_EMPLOYEES (EMP_NAME, EMAIL, JOB_ID, SALARY) VALUES ('Steven','Steven@CORREO.MX', 3, 2100);
INSERT INTO PR_EMPLOYEES (EMP_NAME, EMAIL, JOB_ID, SALARY) VALUES ('STEPHEN','STEPHEN@CORREO.MX', 3, 2100);
INSERT INTO PR_EMPLOYEES (EMP_NAME, EMAIL, JOB_ID, SALARY) VALUES ('Stephen','Stephen@CORREO.MX', 4, 2100);
/
COMMIT;
/
/*BUSQUEDA DE EMPLEADOS QUE SU NOMBRE EMPIECE CON 'STE', TERMINEN EN 'EN' Y EN MEDIO ESTE 'V' O 'PH'*/
SELECT EMP_NAME, EMAIL
FROM PR_EMPLOYEES
WHERE REGEXP_LIKE (EMP_NAME, '^Ste(v|ph)en$', 'i')
ORDER BY EMP_NAME, EMAIL;
/
--USO DE LA FUNCION ANY_VALUE
SELECT * FROM PR_SALES
;
/
--ANY_VALUE ES SIMILAR A MIN Y MAX
SELECT E.EMP_ID, ANY_VALUE(E.EMP_NAME) EMP_NAME, SUM(S.AMOUNT) SALES
FROM PR_EMPLOYEES E, PR_SALES S
WHERE 1=1
AND E.EMP_ID = S.EMP_ID
GROUP BY E.EMP_ID
;
/
--USO DE LA FUNCION RANK PARA MOSTRAR EL RANKING DEL SALARIO DE MAYOR A MENOR EN EL EMPLEO 2
SELECT EMP_NAME, EMAIL, SALARY,
RANK() OVER (PARTITION BY JOB_ID ORDER BY SALARY DESC) RANKING
FROM PR_EMPLOYEES
WHERE 1=1 
AND JOB_ID = 2 --2 ES INGENIERO DE SOFTWARE 
ORDER BY RANKING, EMAIL
;
/
--USO DE LA TABLA ASCII PARA BUSQUEDA DE UNA LETRA EN UN CAMPO
SELECT EMP_NAME, EMAIL
FROM PR_EMPLOYEES
WHERE 1=1
AND ASCII(SUBSTR(EMP_NAME, 1, 1)) = 66 --CARACTER 'B' EN ASCII ES EL NUMERO 66
;
--USO DE LA TABLA ASCII CON LA FUNCION CHR
SELECT CHR(67)||CHR(65)||CHR(84) "Dog"
  FROM DUAL;
  
--USO DE LA FUNCION COALESCE QUE ES SIMILAR A 'CASE WHEN expr1 IS NOT NULL THEN expr1 ELSE expr2 END'
SELECT EMP_NAME, EMAIL, HIRE_DATE
FROM PR_EMPLOYEES
;
--FUNCION COALESCE
SELECT EMP_NAME, EMAIL, COALESCE(HIRE_DATE, HIRE_DATE, SYSDATE) HIRE_DATE1
FROM PR_EMPLOYEES
;
/

--FUNCION REPLACE
SELECT REPLACE('JACK and JUE','J','BL') "Changes"
     FROM DUAL;