SELECT * FROM DEMO_PROJECTS
ORDER BY 1;
/
SELECT * FROM PR_PROJECTS
WHERE 1=1
AND REGEXP_LIKE (UPPER(PROJECTS), 'ACME|BUG|SOFTWARE|LOAD')
;
/
CREATE TABLE PR_DEPARTMENTS (
    DEP_ID NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOT NULL ENABLE,
    DEP_NAME VARCHAR2 (100),
    DEP_PARENT_ID NUMBER,
    STATUS CHAR(1),
    DEP_DESC VARCHAR2 (100),
    CONSTRAINT DEP_ID_PK PRIMARY KEY (DEP_ID)
    USING INDEX ENABLE
);
/
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('DIRECCION GENERAL', NULL, 'A', 'DIRECCION GENERAL');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('FINANZAS', 1, 'A', 'AREA DE FINANZAS');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('RECURSOS HUMANOS', 1, 'A', 'RECURSOS HUMANOS');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('GERENCIA IT', 1, 'A', 'GERENCIA DE TECNOLOGIA');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('CONTABILIDAD', 2, 'A', 'AREA CONTABLE');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('DESARROLLO DE SOFTWARE', 4, 'A', 'DESARROLLO DE SOFTWARE');
INSERT INTO PR_DEPARTMENTS (DEP_NAME, DEP_PARENT_ID, STATUS, DEP_DESC) VALUES ('VENTAS', 2, 'A', 'VENTAS');
COMMIT;
/
SELECT * FROM PR_DEPARTMENTS;
/
--SELECT RECURSIVO PARA MOSTRAR QUE AREA LE REPORTA A QUE AREA
SELECT
    P.DEP_NAME,
    P.DEP_DESC,
    P.STATUS,
    C.DEP_NAME REPORT_TO
    FROM PR_DEPARTMENTS C
    RIGHT JOIN PR_DEPARTMENTS P
    ON P.DEP_PARENT_ID = C.DEP_ID
    ORDER BY P.DEP_ID ASC
    ;