CREATE TABLE "DENTI_USERS"  (
    "ID_USER" NUMBER DEFAULT SEQ_ID_USERS.NEXTVAL NOT NULL,
    "CORREO" VARCHAR2(50) NOT NULL,
    "NOMBRE" VARCHAR2(100) NOT NULL,
    "APELLIDO_PAT" VARCHAR2(100) NOT NULL,
    "APELLIDO_MAT" VARCHAR2(100) NOT NULL,
    "NOMBRE_COMPLETO" VARCHAR2(1000),
    "CONTRASENIA" VARCHAR2(50) NOT NULL,
    "ACTIVO" CHAR(1),
    "FECHA_CREACION" TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
    "ULTIMA_ACTUALIZACION" TIMESTAMP WITH LOCAL TIME ZONE,
    "PREGUNTA_RECU" VARCHAR2(100) NOT NULL,
    "VERIFICACION_CORREO" CHAR(1),
    "VERIFICACION_HTP" NUMBER,
    CONSTRAINT PK_ID_USER PRIMARY KEY (ID_USER)
    );
    /
CREATE INDEX INX_NOMBRE ON DENTI_USERS (NOMBRE);
/

CREATE TABLE DENTI_CITAS (
ID_CITAS NUMBER  DEFAULT SEQ_ID_CITA.NEXTVAL NOT NULL,
ID_USER NUMBER NOT NULL,
FECHA_CITA TIMESTAMP WITH LOCAL TIME ZONE,
CONFIRMACION CHAR(1),
COMENTARIOS VARCHAR2(1000),
CITA_CANCEL CHAR(1),
MOTIVO_CANCEL VARCHAR2(1000),
ACTIVO CHAR(1),
CONSTRAINT PK_ID_CITAS PRIMARY KEY (ID_CITAS),
CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES DENTI_USERS (ID_USER)
);
/
CREATE INDEX INX_FECHACITA ON DENTI_CITAS (FECHA_CITA);

/
CREATE TABLE DENTI_DESCUENTOS (
    ID_DESCUENTO NUMBER DEFAULT SEQ_ID_DESCUENTO.NEXTVAL NOT NULL,
    NOMBRE VARCHAR2(100),
    PORCENTAJE NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(300),
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1),
    CONSTRAINT PK_IDDESC PRIMARY KEY (ID_DESCUENTO)
);
/
CREATE INDEX INX_DESCPORCENTAJE ON DENTI_DESCUENTOS (PORCENTAJE);
/

CREATE TABLE DENTI_TRATAMIENTOS (
    ID_TRATAMIENTO NUMBER DEFAULT SEQ_ID_TRATAMIENTO.NEXTVAL NOT NULL,
    NOMBRE VARCHAR2(500) NOT NULL,
    NOMBRE_MEDICO VARCHAR2(2000) NOT NULL,
    COSTO NUMBER (*,2) NOT NULL,
    ID_DESCUENTO NUMBER,
    ESPECIFICACIONES VARCHAR2(2000) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1),
    CONSTRAINT PK_IDTRATA PRIMARY KEY (ID_TRATAMIENTO),
    CONSTRAINT FK_IDDESC FOREIGN KEY (ID_DESCUENTO) REFERENCES DENTI_DESCUENTOS (ID_DESCUENTO)
);
/
CREATE INDEX INX_TRATANOMBRE ON DENTI_TRATAMIENTOS (NOMBRE);

/
CREATE TABLE DENTI_CITA_DETALLE (
    ID_CITA_DET NUMBER DEFAULT SEQ_ID_CITADET.NEXTVAL NOT NULL,
    ID_CITA NUMBER NOT NULL,
    ID_TRATAMIENTO NUMBER NOT NULL,
    TRATAMIENTO_DETALLE VARCHAR2(2000),
    OBSERVACIONES VARCHAR(2000),
    OBSERVACIONES2 VARCHAR(2000),
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1),
    CONSTRAINT PK_IDCITADET PRIMARY KEY (ID_CITA_DET),
    CONSTRAINT FK_IDCITA FOREIGN KEY (ID_CITA) REFERENCES DENTI_CITAS (ID_CITAS),
    CONSTRAINT FK_IDTRATAMIENTO FOREIGN KEY (ID_TRATAMIENTO) REFERENCES DENTI_TRATAMIENTOS (ID_TRATAMIENTO)
);
/
CREATE TABLE DENTI_DOCTORES (
    ID_DOCTOR NUMBER DEFAULT SEQ_ID_DOCTOR.NEXTVAL NOT NULL,
    ID_USER NUMBER,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_P VARCHAR2(100) NOT NULL,
    APELLIDO_M VARCHAR2(100) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(1000) NOT NULL,
    CORREO VARCHAR2(250) NOT NULL,
    NO_CEDULA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    TELEFONO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1) NOT NULL,
    FECHA_BAJA DATE,
    EDUCACION VARCHAR2(100),
    ESCUELA VARCHAR2(100),
    CONSTRAINT PK_IDDOCTOR PRIMARY KEY (ID_DOCTOR),
    CONSTRAINT FK_IDUSERDOCTOR FOREIGN KEY (ID_USER) REFERENCES DENTI_USERS (ID_USER)
);
/

CREATE TABLE DENTI_PUESTOS (
    ID_PUESTO NUMBER DEFAULT SEQ_ID_PUESTO.NEXTVAL NOT NULL,
    NOMBRE VARCHAR2(250) NOT NULL,
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1) NOT NULL,
    FECHA_BAJA DATE,
    CONSTRAINT PK_IDPUESTO PRIMARY KEY (ID_PUESTO)
);
/
CREATE TABLE DENTI_ESPECIALIDADES (
    ID_ESPECIALIDAD NUMBER DEFAULT SEQ_ID_ESPECIALIDAD.NEXTVAL NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR2(2000) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1) NOT NULL,
    CONSTRAINT PK_IDESPEC PRIMARY KEY (ID_ESPECIALIDAD)
);
/
CREATE TABLE DENTI_DIRECCIONES (
    ID_DIRECCION NUMBER DEFAULT SEQ_ID_DIRECCION.NEXTVAL NOT NULL,
    BILL_FLAG CHAR(1),
    CALLE VARCHAR2(100),
    NUMERO_INT VARCHAR2(100),
    NUMERO_EXT VARCHAR2(100),
    COLONIA VARCHAR2(100),
    CODIGO_POSTAL VARCHAR2(10),
    MUNICIPIO VARCHAR2(100),
    ESTADO VARCHAR2(100),
    PAIS VARCHAR2(100),
    ACTIVO CHAR(1) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_ID_DIRECCION PRIMARY KEY (ID_DIRECCION)
);
/

CREATE TABLE DENTI_CONSULTORIOS (
    ID_CONSULTORIO NUMBER DEFAULT SEQ_ID_CONSULTORIO.NEXTVAL NOT NULL,
    NOMBRE VARCHAR(200) NOT NULL,
    ID_DIRECCION NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(100),
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1),
    CONSTRAINT PK_IDCONSUL PRIMARY KEY (ID_CONSULTORIO),
    CONSTRAINT FK_IDDIRE FOREIGN KEY (ID_DIRECCION) REFERENCES DENTI_DIRECCIONES (ID_DIRECCION)
);
/
CREATE TABLE DENTI_OPINIONES (
    ID_OPINION NUMBER DEFAULT SEQ_ID_OPINION.NEXTVAL NOT NULL,
    OPINION VARCHAR(2000) NOT NULL,
    PONDERACION NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ID_DOCTOR NUMBER,
    ID_TRATAMIENTO NUMBER,
    ID_CONSULTORIO NUMBER,
    ACTIVO CHAR(1),
    CONSTRAINT FK_IDDOCOPINION FOREIGN KEY (ID_DOCTOR) REFERENCES DENTI_DOCTORES (ID_DOCTOR),
    CONSTRAINT FK_IDTRATAOPINION FOREIGN KEY (ID_TRATAMIENTO) REFERENCES DENTI_TRATAMIENTOS (ID_TRATAMIENTO),
    CONSTRAINT FK_IDCONSULOPINION FOREIGN KEY (ID_CONSULTORIO) REFERENCES DENTI_CONSULTORIOS (ID_CONSULTORIO)
);
/
CREATE TABLE DENTI_DOCTOR_DETALLE (
    ID_DETALLE NUMBER DEFAULT SEQ_ID_CONDETALLE.NEXTVAL NOT NULL,
    ID_DOCTOR NUMBER NOT NULL,
    ID_ESPECIALIDAD NUMBER NOT NULL,
    ID_CONSULTORIO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    ACTIVO CHAR(1) NOT NULL,
    FECHA_BAJA DATE,
    CONSTRAINT FK_IDDOCDETDOC FOREIGN KEY (ID_DOCTOR) REFERENCES DENTI_DOCTORES (ID_DOCTOR),
    CONSTRAINT FK_IDDOCDETESP FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES DENTI_ESPECIALIDADES (ID_ESPECIALIDAD),
    CONSTRAINT FK_IDDOCDETCONSU FOREIGN KEY (ID_CONSULTORIO) REFERENCES DENTI_CONSULTORIOS (ID_CONSULTORIO)
);

/
/* OBSOLETO
CREATE TABLE DENTI_CONSULTORIO_DETALLE (
    ID_CONSULDETALLE NUMBER DEFAULT SEQ_ID_CONDETALLE.NEXTVAL NOT NULL,
    ID_CONSULTORIO NUMBER NOT NULL,
    ID_DIRECCION NUMBER NOT NULL,
    ACTIVO CHAR(1) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT FK_CONDETCONSUL FOREIGN KEY (ID_CONSULTORIO) REFERENCES DENTI_CONSULTORIOS (ID_CONSULTORIO),
    CONSTRAINT FK_CONDETDIRE FOREIGN KEY (ID_DIRECCION) REFERENCES DENTI_DIRECCIONES (ID_DIRECCION)
);
DROP TABLE DENTI_CONSULTORIO_DETALLE;
*/
/
CREATE TABLE DENTI_VISITANTES (
    ID_VISITANTE NUMBER DEFAULT SEQ_ID_VISITANTE.NEXTVAL NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    ACTIVO CHAR(1) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSDATE,
    FECHA_BAJA TIMESTAMP,
    CONSTRAINT PK_IDVISIT PRIMARY KEY (ID_VISITANTE)
);