SELECT * FROM ALL_TABLES
WHERE TABLE_NAME LIKE 'DENT%'
;

SELECT * FROM DENTI_USERS;
SELECT * FROM DENTI_DOCTORES;
SELECT * FROM DENTI_DIRECCIONES;
SELECT * FROM DENTI_CONSULTORIOS;
SELECT * FROM DENTI_ESPECIALIDADES;
SELECT * FROM DENTI_DOCTOR_DETALLE;
SELECT * FROM DENTI_VISITANTES;

INSERT INTO DENTI_VISITANTES (NOMBRE,CORREO,ACTIVO,FECHA_CREACION,FECHA_BAJA)
VALUES ('BRANDON2','CORREO@HOTMAIL.COM','V',SYSDATE,SYSDATE);
COMMIT;

INSERT INTO DENTI_USERS (CORREO,NOMBRE,APELLIDO_PAT,APELLIDO_MAT,NOMBRE_COMPLETO,CONTRASENIA,ACTIVO,FECHA_CREACION,ULTIMA_ACTUALIZACION,PREGUNTA_RECU,VERIFICACION_CORREO,VERIFICACION_HTP) 
VALUES ('correo@hotmail.com','Persona','Apellido','Appellido2','Persona Apellido Apellido2',FUN_ENCRIPTA('123456789B'),'V',TO_DATE('12-DEC-2023'),TO_DATE('12-DEC-2023'),'COSAS','F',1111 );

INSERT INTO DENTI_USERS (CORREO,NOMBRE,APELLIDO_PAT,APELLIDO_MAT,NOMBRE_COMPLETO,CONTRASENIA,ACTIVO,FECHA_CREACION,PREGUNTA_RECU) 
VALUES ('doc@hotmail.com','Alfonso','Rodillo','Izquierda','Alfonso Rodillo Izquierda',FUN_ENCRIPTA('123456789'),'V',SYSDATE,'COSA2' );
COMMIT;

INSERT INTO DENTI_DOCTORES (ID_USER,NOMBRE,APELLIDO_P,APELLIDO_M,NOMBRE_COMPLETO,CORREO,NO_CEDULA,DESCRIPCION,TELEFONO,ACTIVO)
VALUES (2,'Alfonso','Rodillo','Izquierda','Alfonso Rodillo Izquierda','doc@hotmail.com','000000','N/A','8888888','V');
COMMIT;

INSERT INTO DENTI_DIRECCIONES (BILL_FLAG,CALLE,NUMERO_INT,NUMERO_EXT,COLONIA,CODIGO_POSTAL,ESTADO,PAIS,ACTIVO,DESCRIPCION, MUNICIPIO)
VALUES ('F','BLVD. NAZARIO ORTIZ','2800','','LOS LAGOS',67250,'COAHUILA','MX','V','N/A','SALTILLO');
COMMIT;

INSERT INTO DENTI_CONSULTORIOS (NOMBRE,ID_DIRECCION,DESCRIPCION,ACTIVO)
VALUES ('DENTAL ROOM',1,'CONSULTORIO DENTAL GENERAL','V');
COMMIT;

INSERT INTO DENTI_ESPECIALIDADES (NOMBRE,DESCRIPCION,ACTIVO)
VALUES ('ODONTOLOGIA PEDIATRA', 'N/A','V');
INSERT INTO DENTI_ESPECIALIDADES (NOMBRE,DESCRIPCION,ACTIVO)
VALUES ('URGENCIAS DENTALES', 'N/A','V');
INSERT INTO DENTI_ESPECIALIDADES (NOMBRE,DESCRIPCION,ACTIVO)
VALUES ('ORTODONCIA', 'N/A','V');
INSERT INTO DENTI_ESPECIALIDADES (NOMBRE,DESCRIPCION,ACTIVO)
VALUES ('ODONTOLOGIA PREVENTIVA', 'N/A','V');
COMMIT;

INSERT INTO DENTI_DOCTOR_DETALLE (ID_DOCTOR ,ID_ESPECIALIDAD,ID_CONSULTORIO,ACTIVO)
VALUES (2,1,2,'V');
INSERT INTO DENTI_DOCTOR_DETALLE (ID_DOCTOR ,ID_ESPECIALIDAD,ID_CONSULTORIO,ACTIVO)
VALUES (2,2,2,'V');
INSERT INTO DENTI_DOCTOR_DETALLE (ID_DOCTOR ,ID_ESPECIALIDAD,ID_CONSULTORIO,ACTIVO)
VALUES (2,3,2,'V');
COMMIT;
