CREATE SEQUENCE SEQ_ID_CITA
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_CITA.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_CITADET
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_CITADET.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_USERS
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_USERS.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_VISITANTE
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_VISITANTE.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_TRATAMIENTO
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_TRATAMIENTO.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_DESCUENTO
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_DESCUENTO.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_DOCTOR
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_DOCTOR.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_PUESTO
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_PUESTO.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_ESPECIALIDAD
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_ESPECIALIDAD.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_CONSULTORIO
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_CONSULTORIO.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_DIRECCION
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_DIRECCION.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_OPINION
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_OPINION.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_DOCDETALLE
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_DOCDETALLE.NEXTVAL FROM DUAL;
/
CREATE SEQUENCE  SEQ_ID_CONDETALLE
START WITH 0
INCREMENT BY 1
MAXVALUE 999999
MINVALUE 0
NOCACHE
CYCLE;
/
SELECT SEQ_ID_CONDETALLE.NEXTVAL FROM DUAL;
/